### ISSUE TITLE
Add BP_KEEP_FILES option for Java family buildpacks

### ISSUE THREAD

**Issue by dfreilich** [paketo-buildpacks/libbs#103]
## What happened?

* What were you attempting to do?
I have a Java server, which serves a front-end built by an embedded Yarn app (e.g., the `yarn` app lives in the `client` directory of the repo, and builds a `files/static/...` directory that the server provides to consumers). As such, I was trying to orchestrate a build by first running the `nodejs` buildpack, and then the `Java` buildpack. 

* What did you expect to happen?
I was expecting that the compiled front-end files would be available on the image, but because they were part of the source files (which are cleaned up by `libbs` [here](https://github.com/paketo-buildpacks/libbs/blob/96f9ae944c5244df2a2ec60c70f374f9b2495425/application.go#L136)), they were removed 

* What would you like?
I'd like to have an environment variable which functions similar to the `BP_KEEP_FILES` in Go, allowing users to specify source directories that `libbs` should not clean up

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
I'm using `pack v0.23`

* What buildpacks are you using? Please include versions.
`paketo-buildpacks/java@5.21.0`
`paketo-buildpacks/nodejs@0.9.0`

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
`paketobuildpacks/builder:full`

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
+1 for this. Seems like a good enhancement request. We've been discussing this as a project, how to handle deleting source files in a consistent way and there is [an RFC open about that](https://github.com/paketo-buildpacks/rfcs/pull/129). I would want to hold off implementing something until that RFC works its way through so that we can be compliant with the RFC. We may not use the buildpack mentioned there, but I want to minimally make sure we're using the same interface & env variables for configuration.

In the meantime, you might be able to work around this in a couple of ways:

1. After you build the files with the Node.js buildpack, move them into a location so that they get bundled into your JAR file. The JAR file will be persisted and exploded into the `/workspace` directory. So if you included them in your JAR file under `files/static/...` they would be extracted to `/workspace/files/static/...`.

2. You might also try using the support we just added for multi-artifact builds. The Maven (and other build tools buildpacks) can now save multiple artifacts from the build process. It still defaults to a single JAR file, but you can adjust `$BP_MAVEN_BUILT_ARTIFACT` so that it matches a folder or multiple files (supports glob syntax).  If it matches a directory or multiple files, all of those files are stashed in the layer and then restored to `/workspace`.

    The drawback of this approach is that executabe-jar and other buildpacks (except native-image) do not know how to run your application in this case. They expect the exploded JAR file structure in `/workspace`. If you have multiple build artifacts, you would need to include a Procfile and have the start command specified there, which while possible is not ideal.

At some point, we might add support to executable jar for multiple files. Possibly allow you to point to which of the files is the executable jar, or search them all for the executable jar (and similar for Tomcat). It is not a high priority at the moment though.

**Comment by dmikusa-pivotal** [comment]
Update: we are in a position where this can be implemented now. The source removal RFC has been approved & implemented. The source removal buildpack is part of Paketo. It has also been updated so that we can consume the code as a library, which is what's necessary for integration into libbs.

A very similar integration was done [here](https://github.com/paketo-community/cargo/pull/171). That code is not using libbs, but is heavily based on it. The integration into libbs should be very similar.
